# Generated by Django 2.2.3 on 2019-07-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("ttl", models.PositiveSmallIntegerField(default=86400)),
                ("path", models.CharField(max_length=65)),
                ("filename", models.CharField(max_length=1024)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Downloading"), (1, "Completed"), (2, "Failed")],
                        default=0,
                    ),
                ),
            ],
        )
    ]
