# Generated by Django 2.2.3 on 2019-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiss_cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_usage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
