# Generated by Django 2.2.3 on 2019-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0004_remove_resource_filename")]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="content_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="content_type",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
