# Generated by Django 2.2.3 on 2019-07-31 11:51

from django.db import migrations, models


def create_statistics(apps, schema_editor):
    Statistic = apps.get_model("kiss_cache", "Statistic")

    STAT_DOWNLOAD, STAT_UPLOAD = range(2)
    Statistic.objects.get_or_create(stat=STAT_DOWNLOAD)
    Statistic.objects.get_or_create(stat=STAT_UPLOAD)


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0007_resource_created_at")]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "stat",
                    models.IntegerField(
                        choices=[(0, "Download"), (1, "Upload")],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(create_statistics),
    ]
