# Generated by Django 2.2.3 on 2019-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0008_statistic")]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="value",
            field=models.BigIntegerField(default=0),
        )
    ]
