# Generated by Django 2.2.12 on 2020-04-10 12:13

from django.db import migrations, models


def create_statistics(apps, schema_editor):
    Resource = apps.get_model("kiss_cache", "Resource")
    STATE_SCHEDULED, STATE_DOWNLOADING, STATE_FINISHED = range(3)

    Statistic = apps.get_model("kiss_cache", "Statistic")
    STAT_DOWNLOAD, STAT_UPLOAD, STAT_SUCCESSES, STAT_FAILURES = range(4)
    (successes, _) = Statistic.objects.get_or_create(stat=STAT_SUCCESSES)
    (failures, _) = Statistic.objects.get_or_create(stat=STAT_FAILURES)

    query = Resource.objects.filter(state=STATE_FINISHED)
    successes.value = query.filter(status_code=200).count()
    successes.save()
    failures.value = query.exclude(status_code=200).count()
    failures.save()


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0010_remove_resource_path")]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="stat",
            field=models.IntegerField(
                choices=[
                    (0, "Download"),
                    (1, "Upload"),
                    (2, "Successes"),
                    (3, "Failures"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RunPython(create_statistics),
    ]
