# Generated by Django 2.2.12 on 2020-04-20 14:05

from django.db import migrations, models


def create_statistics(apps, schema_editor):
    Statistic = apps.get_model("kiss_cache", "Statistic")
    STAT_DOWNLOAD, STAT_UPLOAD, STAT_SUCCESSES, STAT_FAILURES, STAT_REQUESTS = range(5)
    Statistic.objects.get_or_create(stat=STAT_REQUESTS)


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0011_add_more_statistics")]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="stat",
            field=models.IntegerField(
                choices=[
                    (0, "Download"),
                    (1, "Upload"),
                    (2, "Successes"),
                    (3, "Failures"),
                    (4, "Requests"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RunPython(create_statistics),
    ]
