# Generated by Django 2.2.16 on 2020-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiss_cache", "0012_add_statistic_requests")]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="content_length",
            field=models.BigIntegerField(blank=True, null=True),
        )
    ]
