# Generated by Django 2.2.24 on 2021-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiss_cache", "0013_resource_content_length_big_integer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
